on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    container: continuumio/miniconda3
    steps:

      - uses: actions/checkout@v1

      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: /opt/conda
          key: ${{ hashFiles('env.yml') }}-${{ hashFiles('env-r.yml') }}

      - name: Rebuild cache
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: |
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
          conda config --set channel_priority strict

          conda install mamba -y
          mamba env create -n lcdb-wf-test --file env.yml
          mamba env create -n lcdb-wf-test-r --file env-r.yml

      - name: STAR available?
        shell: bash
        run: |
          source activate lcdb-wf-test
          STAR --version
